export const visualOptions = {
  marginTop: {
    type: 'number',
    label: 'Margin (top)',
    default: 10,
    group: 'artboard',
  },
  marginRight: {
    type: 'number',
    label: 'Margin (right)',
    default: 50,
    group: 'artboard',
  },
  marginBottom: {
    type: 'number',
    label: 'Margin (bottom)',
    default: 10,
    group: 'artboard',
  },
  marginLeft: {
    type: 'number',
    label: 'Margin (left)',
    default: 0,
    group: 'artboard',
  },
  showLegend: {
    type: 'boolean',
    label: 'Show legend',
    default: false,
    group: 'artboard',
  },
  linksOpacity: {
    type: 'number',
    label: 'Links opacity (0-1)',
    default: 0.5,
    step: 0.1,
    min: 0,
    max: 1,
    group: 'chart',
  },
  linksCurveness: {
    type: 'number',
    label: 'Links curveness (0.3-0.7)',
    default: 0.3,
    step: 0.1,
    min: 0.3,
    max: 0.7,
    group: 'chart',
  },
  draggable: {
    type: 'boolean',
    label: 'Draggable',
    group: 'chart',
    default: false,
  },
  showLabels: {
    type: 'text',
    label: 'Show node labels',
    group: 'labels',
    options: ['false', 'largeNodes', 'true'],
    default: 'largeNodes',
  },
  labelFontSize: {
    type: 'number',
    label: 'Label font size',
    default: 12,
    group: 'labels',
    disabled: {
      showLabels: false,
    },
  },
  rotateLabel: {
    type: 'boolean',
    label: 'Rotate label',
    default: true,
    group: 'labels',
    disabled: {
      showLabels: false,
    },
  },
  showTooltip: {
    type: 'boolean',
    label: 'Show tooltip',
    default: true,
    group: 'Tooltip',
  },
  isMonetaryValue: {
    type: 'boolean',
    label: 'Is monetary value?',
    default: false,
    group: 'Tooltip',
    disabled: {
      showTooltip: false,
    },
  },
}
